### ISSUE TITLE
Error while trying to connect

### ISSUE THREAD

**Issue by Warlord77** [kivy/kivy-remote-shell#8]
Unable to negotiate with x.y.z.r: no matching key exchange method found.
Their offer: diffie-hellman-group1-sha1

**Comment by Warlord77** [comment]
Possible workaround
 ssh -oKexAlgorithms=+diffie-hellman-group1-sha1 admin@x.y.z.r -p8000

**Comment by akshayaurora** [comment]
Fixed with the latest changes in p4a
