### ISSUE TITLE
Provide pre-built APK

### ISSUE THREAD

**Issue by kkwaiser** [kivy/kivy-remote-shell#9]
A feature request of sorts. Can you provide, on the GitHub page, the Kivy Remote Shell APK? That or provide better build instructions [as user support can be sparse](https://groups.google.com/forum/#!topic/kivy-users/eT-mNDDeliU). 

Requiring users to build the APK presents a significant hurdle to gaining users. I spent 6 hours trying to get it built and never got a fully-functioning version. Fortunately, I [stumbled on the APK](https://github.com/kiok46/Pycon-Presentation) and it worked immediately.

**Comment by akshayaurora** [comment]
Link to pre-built apk available in README now.
